version: '3.8'

services:
  api-chascas-container:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-chascas:latest
    container_name: api-chascas-container
    ports:
      - "5000:80"
    depends_on:
      - mysql-container  # Asegura que el contenedor de MySQL esté en ejecución antes de iniciar la API

  mysql-container:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: a12345
      MYSQL_DATABASE: chascas
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
