version: '3.8'

services:
  api-chascas-container:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-chascas:latest
    container_name: api-chascas-container
    ports:
      - "5000:80"
    depends_on:
      - postgres-container  # Asegura que el contenedor de PostgreSQL esté en ejecución antes de iniciar la API

  postgres-container:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin1
      POSTGRES_DB: chascas
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:

